export const ERROR_CODES = {
	VALIDATION_ERROR: "VALIDATION_ERROR",
	UNAUTHORIZED: "UNAUTHORIZED",
	INVALID_TOKEN: "INVALID_TOKEN",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",
	FORBIDDEN: "FORBIDDEN",
	CONFLICT: "CONFLICT",
	NOT_FOUND: "NOT_FOUND",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
